### ISSUE TITLE
Problem compiling on Linux

### ISSUE THREAD

**Issue by tritao** [FlaxEngine/FlaxEngine#1734]
**Issue description:**

Cannot compile from source on a clean checkout, Linux Mint 21 (Ubuntu 22.04 based).

**Steps to reproduce:**

`FlaxEngine$ git reset --hard`
```
HEAD is now at 8b096a928 Fixes
```

`FlaxEngine$ ./GenerateProjectFiles.sh`
```
Generating Flax Engine project files...
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Missing VulkanSDK.
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Cannot use system-installed VulkanSDK at /usr/include when building for platform Android
Building C# bindings...
Task dotnet exec "/usr/lib/dotnet/sdk/7.0.112/Roslyn/bincore/csc.dll" /noconfig /shared @"FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/FlaxEngine.CSharp.response" failed with exit code 1
```

`FlaxEngine$ dotnet exec "/usr/lib/dotnet/sdk/7.0.112/Roslyn/bincore/csc.dll" /noconfig /shared`
```@"FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/FlaxEngine.CSharp.response"
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Engine/Engine.Bindings.Gen.cs(565,40,565,62): error SYSLIB1051: The type 'FlaxEngine.Window' is not supported by source-generated P/Invokes. The generated source will not handle marshalling of the return value of method 'Internal_GetMainWindow'.
FlaxEngine/Source/Engine/Core/Config/GameSettings.cs(145,96,145,117): error CS0246: The type or namespace name 'LinuxPlatformSettings' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Networking/Networking.Bindings.Gen.cs(1469,20,1469,32): error CS0246: The type or namespace name 'PlatformType' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Networking/Networking.Bindings.Gen.cs(1470,20,1470,36): error CS0246: The type or namespace name 'ArchitectureType' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Networking/Networking.Bindings.Gen.cs(1538,16,1538,28): error CS0246: The type or namespace name 'PlatformType' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Networking/Networking.Bindings.Gen.cs(1543,16,1543,32): error CS0246: The type or namespace name 'ArchitectureType' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Engine/Engine.Bindings.Gen.cs(559,30,559,40): error CS0053: Inconsistent accessibility: property type 'Window' is less accessible than property 'Screen.MainWindow'
FlaxEngine/Source/Engine/Platform/Platform.cs(24,46,24,59): error CS0246: The type or namespace name 'NetworkSocket' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Platform.cs(40,46,40,59): error CS0246: The type or namespace name 'NetworkSocket' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Platform.cs(40,81,40,96): error CS0246: The type or namespace name 'NetworkEndPoint' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Platform.cs(55,45,55,58): error CS0246: The type or namespace name 'NetworkSocket' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Platform.cs(71,45,71,58): error CS0246: The type or namespace name 'NetworkSocket' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Platform.cs(71,82,71,97): error CS0246: The type or namespace name 'NetworkEndPoint' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Window.cs(331,67,331,81): error CS0246: The type or namespace name 'WindowHitCodes' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Window.cs(341,48,341,62): error CS0246: The type or namespace name 'WindowHitCodes' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Window.cs(349,18,349,32): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Window.cs(360,18,360,32): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Window.cs(371,18,371,32): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Window.cs(387,42,387,55): error CS0246: The type or namespace name 'ClosingReason' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Window.cs(145,21,145,35): error CS0246: The type or namespace name 'WindowHitCodes' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Window.cs(15,46,15,59): error CS0246: The type or namespace name 'ClosingReason' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/Platform/Window.cs(22,25,22,39): error CS0246: The type or namespace name 'WindowHitCodes' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(335,24,335,28): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(343,25,343,29): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(351,30,351,34): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(360,43,360,47): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(369,51,369,55): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(378,68,378,72): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(387,45,387,49): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(397,69,397,73): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(407,52,407,56): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(417,48,417,52): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(427,56,427,60): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Cache/Intermediate/FlaxGame/Linux/x64/Release/Online/Online.Bindings.Gen.cs(437,52,437,56): error CS0246: The type or namespace name 'User' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/Control.cs(317,24,317,34): error CS0246: The type or namespace name 'CursorType' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/CanvasRootControl.cs(78,25,78,35): error CS0246: The type or namespace name 'CursorType' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/Control.cs(966,24,966,38): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs(1282,25,1282,39): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/CanvasRootControl.cs(277,25,277,39): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/Control.cs(940,24,940,38): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs(1199,25,1199,39): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/CanvasRootControl.cs(286,25,286,39): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/Control.cs(954,24,954,38): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/ContainerControl.cs(1224,25,1224,39): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/CanvasRootControl.cs(304,25,304,39): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/CanvasScaler.cs(449,25,449,39): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/CanvasScaler.cs(456,25,456,39): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/CanvasScaler.cs(463,25,463,39): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/Panels/Panel.cs(543,25,543,39): error CS0246: The type or namespace name 'DragDropEffect' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/Tooltip.cs(33,23,33,29): error CS0053: Inconsistent accessibility: property type 'Window' is less accessible than property 'Tooltip.Window'
FlaxEngine/Source/Engine/UI/GUI/WindowRootControl.cs(147,25,147,35): error CS0246: The type or namespace name 'CursorType' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/WindowRootControl.cs(22,23,22,29): error CS0053: Inconsistent accessibility: property type 'Window' is less accessible than property 'WindowRootControl.Window'
FlaxEngine/Source/Engine/UI/GUI/WindowRootControl.cs(111,27,111,40): error CS0246: The type or namespace name 'ClosingReason' could not be found (are you missing a using directive or an assembly reference?)
FlaxEngine/Source/Engine/UI/GUI/WindowRootControl.cs(111,50,111,63): error CS0103: The name 'ClosingReason' does not exist in the current context
```

**Flax version:**

```
HEAD is now at 8b096a928 Fixes
```

**Comment by MineBill** [comment]
Run `dotnet --list-sdks` and post your results.

**Comment by mafiesto4** [comment]
Could you attach last build log file `Cache/Intermediate/Log.txt`? (from FlaxEngine folder)

**Comment by mafiesto4** [comment]
Ah ok so it's regression from #1569 - building C# FlaxGame is failing for some reason due to missing codegen

**Comment by mafiesto4** [comment]
Fixed in 55ad5ae367a094105b2dec06e43433cf70593a1d.
